version: "3"
services:
  web:
    build: .
    container_name: apache_web
    restart: always
    volumes:
      - ./web:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
      - mailhog 
    links:
      - db
      - mailhog
    networks:
      default:
        aliases:
          - crmmw.local  
          - indicadores.local
          - teste.local  
          - email.local
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    environment:
      - SA_PASSWORD=usuario@senha
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - ./banco:/banco
      - ./banco/mssql:/var/opt/mssql
      - ./banco/sqlserver:/var/opt/sqlserver 
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports: 
    - 1025:1025
    - 8025:8025  