version: "3"
services:
  web:
    build: .
    container_name: apache_web
    restart: always
    volumes:
      - ./web:/var/www/html
    ports:
      - "80:80"
    networks:
      default:
        aliases:
          - crmmw.local  
          - indicadores.local
          - teste.local  
          - at.local  
  
 