version: "3"
services:
  web:
    build: .
    container_name: apache_web
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db 
    links:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    environment:
      - SA_PASSWORD=usuario@senha
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
