version: "3"
services:
  web:
    build: .
    container_name: apache_web
    restart: always
    volumes:
      - ./web:/var/www/html
      - /home/$USER/.ssh:/home/.ssh 
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    links:
      - db
    networks:
      default:
        aliases:
          - crmmw.local  
          - indicadores.local
          - teste.local  
          - email.local
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    environment:
      - SA_PASSWORD=usuario@senha
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - ./banco:/banco
      - ./banco/mssql:/var/opt/mssql
      - ./banco/sqlserver:/var/opt/sqlserver 
